import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { copyFileSync, existsSync, mkdirSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
});

if (prod) {
  await context.rebuild();
  if (!existsSync('dist')) mkdirSync('dist');
  copyFileSync('manifest.json', 'dist/manifest.json');
  if (existsSync('styles.css')) copyFileSync('styles.css', 'dist/styles.css');
  if (existsSync('assets')) {
    if (!existsSync('dist/assets')) mkdirSync('dist/assets', { recursive: true });
    ['wechat-donate.jpg'].forEach(f => {
      const src = `assets/${f}`;
      if (existsSync(src)) {
        copyFileSync(src, `dist/assets/${f}`);
        console.log(`Copied ${src} -> dist/assets/${f}`);
      }
    });
  }
  process.exit(0);
} else {
  await context.watch();
}
